GEMINI_API_KEY = "AIzaSyARYHy5tB18hTyLHdY5D1G02XY5AWuD4FU"


LIVEKIT_URL="wss://rag-voicechat-3c5v4fnk.livekit.cloud"
LIVEKIT_API_KEY="APIVzqGDbmn3sBd"
LIVEKIT_API_SECRET="uEFqIqmI3sQLf9Hh13Y1XvDysJAfGNsRQRdm1TiK6xn"
